version: '3'
services:
  ubuntu-dev:
    tty: true
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ubuntu-dev
    user: trilla
    volumes:
      - /home/trilla/code:/home/trilla/code
